### ISSUE TITLE
request for Miku_device_xiaomi_zijin

### ISSUE THREAD

**Issue by feilongfl** [Diva-Room/Miku_device_deps_zijin#1]
您好，最近我购入了一台civi 1s，对原生系统比较感兴趣，
我尝试构建了miku ui，但是发现没有权限访问`Miku_device_deps_zijin`仓库。
冒昧问下您是否有公开`Miku_device_deps_zijin`仓库的计划

**Comment by AmeChanRain** [comment]
小伙伴你好！目前zijin&mona仓库的闭源是受到了一些**不愉快的历史原因**的影响，后续可能会在进一步完善后开源哦。
(*^_^*)感谢你对Miku UI的支持！
